export default {
  "login": "ShafiqullahTurkmen",
  "id": 47690479,
  "node_id": "MDQ6VXNlcjQ3NjkwNDc5",
  "avatar_url": "https://avatars.githubusercontent.com/u/47690479?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/ShafiqullahTurkmen",
  "html_url": "https://github.com/ShafiqullahTurkmen",
  "followers_url": "https://api.github.com/users/ShafiqullahTurkmen/followers",
  "following_url": "https://api.github.com/users/ShafiqullahTurkmen/following{/other_user}",
  "gists_url": "https://api.github.com/users/ShafiqullahTurkmen/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/ShafiqullahTurkmen/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/ShafiqullahTurkmen/subscriptions",
  "organizations_url": "https://api.github.com/users/ShafiqullahTurkmen/orgs",
  "repos_url": "https://api.github.com/users/ShafiqullahTurkmen/repos",
  "events_url": "https://api.github.com/users/ShafiqullahTurkmen/events{/privacy}",
  "received_events_url": "https://api.github.com/users/ShafiqullahTurkmen/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Shafiqullah Turkmen",
  "company": null,
  "blog": "",
  "location": "Istanbul / Turkey",
  "email": null,
  "hireable": true,
  "bio": null,
  "twitter_username": null,
  "public_repos": 29,
  "public_gists": 0,
  "followers": 43,
  "following": 44,
  "created_at": "2019-02-16T11:48:40Z",
  "updated_at": "2023-06-17T17:46:26Z"
};
